### ISSUE TITLE
[AWS::Redshift::Cluster] Drift Detection issue for Classic property under AWS::Redshift::Cluster resource

### ISSUE THREAD

**Issue by FarrOut** [aws-cloudformation/aws-cloudformation-resource-providers-redshift#131]
There is an issue with this resource type whereby false-positive drift is reported for the Classic property. A similar [ticket](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1204) has been opened in the Cloudformation roadmap, but opening another here as this team is responsible for this resource type handler.

Will be happy to provide any further info as required.

---

**Name of the resource**
AWS::Redshift::Cluster

**Issue Description**
The Classic property for the AWS::Redshift::Cluster resource is marked as drifted when its value is specified as false.

**Expected Behavior**
The Classic property should be IN_SYNC or NOT_CHECKED status.

**Observed Behavior**
The Classic property is marked as REMOVE with
```
expected = false
actual = -
```

**Test Cases**

Steps to reproduce -

- Create Stack using following template -

```
Resources:
    myCluster:
      Type: 'AWS::Redshift::Cluster'
      Properties:
        DBName: mydb
        MasterUsername: master
        MasterUserPassword: xxxxxxxxxx
        NodeType: ds2.xlarge
        ClusterType: single-node
        Classic: false
```

- Run drift detection
- View drift results
